### ISSUE TITLE
jspm-git@beta is trying to resolve a json file for the entire user

### ISSUE THREAD

**Issue by ronzeidman** [Orbs/jspm-git#29] opened 2016-03-27 09:43 UTC
When I installed "bitbucket:" repo the packageConfigPaths has become:
```js
"bitbucket:*.json"
```
instead of
```js
"bitbucket:*/*.json"
```

**Comment by subesokun** [comment] 2016-03-27 17:31
Hi @ronzeidman, I'll try to analyze this issue as soon as I can. But so far I can say that this config path gets generated by jspm, so I'll try to figure out what has changed there.

**Comment by abhipanda** [comment] 2016-08-02 20:52
Hi @subesokun - did you get a chance to check this?

**Comment by subesokun** [comment] 2016-08-03 19:44
@abhipanda, sorry didn't have had a chance yet to investigate this issue. Any help at debugging would be appreciated.

**Comment by subesokun** [comment] 2016-08-06 10:15
closing as duplicate of #47

**Closed by subesokun** 2016-08-06 10:15 UTC
Labels: help wanted
