### ISSUE TITLE
Module name not as expected with jspm@0.17.0-beta.18+

### ISSUE THREAD

**Issue by unional** [Orbs/jspm-git#46] opened 2016-07-07 00:25 UTC
I'm using `jspm-git@beta` for a private bitbucket server. Bitbucket server is organized as `<project>/<repo>` e.g. `myteam/myModule`.

in `jspm@0.17.0-beta.17`, when I install the module with `jspm i bit:myteam/myModule`, it is installed with `myModule` as the name of the module.

But since `jspm@0.18.0-beta.18` and onwards, it is installed as `myteam/myModule`.

**Comment by unional** [comment] 2016-07-15 17:41
I can confirm that it is installed as `myModule` for `jspm@0.17.0-beta-17` or prior on new install.

Do you mean it being installed as `myteam/myModule` is expected?
This would make it very cumbersome to use.
For example you have a private github repo: `http://github.mycompany.local`
You set it up through:

```sh
jspm registry create gh jspm-git
> url: http://github.mycompany.local
...
```

Then you use it as:
```sh
jspm install gh:someone/mymodule
```
and it is installed as `someone/mymodule`

**Comment by subesokun** [comment] 2016-07-15 18:07
Yes if I'm not completely wrong then this is the expected behaviour that has been always like that. If you install modules like `jspm i bit:myteam/myrepo` then you've to reference them as `myteam/myrepo`. Only if you do a `jspm i myrepo=bit:myteam/myrepo` then it'll be aliased. Otherwise what would happen if you do a `jspm i bit:myteam/myrepo bit:otherteam/myrepo`...? Only one of them can get the `myrepo` alias.

Anyhow this is an behaviour that can't be influenced by jspm-git as this logic is implemented directly in the jspm core. So you'd have to file an issue there or seek for help in the jspm slack channel.

**Comment by tauren** [comment] 2016-11-13 10:06
@subesokun closing this issue since it is outside scope of jspm-git. Feel free to reopen if necessary.

**Closed by tauren** 2016-11-13 10:06 UTC
Labels: support
